### ISSUE TITLE
Save password in client cookies

### ISSUE THREAD

**Issue by Alextopher** [COSI-Lab/go-talks#4]
We have a tradeoff between security and convenience. Currently go-talks requires clients joining from outside trusted subsets to enter a password. This imposes an inconvenience and in return we get more access control. 

Talks is able to store authentication status during a single session, this should be made persistent on the client side so a user should only ever have to enter the password once.

**Comment by shayanshabani** [comment]
Would you please assign me?

**Comment by Alextopher** [comment]
@shayanshabani are you a Clarkson student or do you use this software? What brings you to wanting to contribute here?

**Comment by shayanshabani** [comment]
I found your issue on goodfirstissues, I am a computer engineering student currently taking a web programming course.
I opened this pr #6 , I hope this helps.
